eventos/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.ListPostsView.as_view(), name='list_posts'),
    path('sharepost/<int:pk>/', views.FormPostView.as_view(), name="sharepost"),
    path('logout/', views.LogoutUserView.as_view(), name="logoutuser"),
    path('comment/<int:pk>/', views.comment_views.as_view(), name="comment"),
    path('cadastrouser/', views.CadUserView.as_view(), name="cadastrouser"),
    path('login/', views.LoginUserView.as_view(), name="loginuser"),
    path('<slug:slug>/', views.DetailPostView.as_view(), name="detail_post"),

]

events/urls.py
from django.urls import path
from . import views

app_name = 'events'
urlpatterns = [
    path('', views.EventoListView.as_view(), name='list_eventos'),
    path('sharepost/<int:pk>/', views.FormEventoView.as_view(), name="sharepost"),
    path('logout/', views.LogoutUserView.as_view(), name="logoutuser"),
    path('comment/<int:pk>/', views.comment_views.as_view(), name="comment"),
    path('cadastrouser/', views.CadUserView.as_view(), name="cadastrouser"),
    path('login/', views.LoginUserView.as_view(), name="loginuser"),
    path('<slug:slug>/', views.EventoDetailView.as_view(), name='detail_event')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('events.urls', 'events'), namespace='events')),
]

events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='publish')


class Evento(models.Model):
    titulo = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, blank=True)  # <-- ADICIONE ESTA LINHA!
    descricao = models.TextField()
    data = models.DateTimeField()
    local = models.CharField(max_length=200)
    organizador = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        limit_choices_to={'is_superuser': True},
        related_name='eventos_organizados',
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.titulo)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.titulo

class Inscricao(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    data_inscricao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.usuario.username} - {self.evento.titulo}"

class Comment(models.Model):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField('Nome', max_length=250)
    email = models.EmailField('Email')
    comment = models.TextField('Comentário')
    created = models.DateTimeField('Data da Criação', auto_now_add=True)
    active = models.BooleanField('Ativo', default=False)

    class Meta:
        verbose_name = 'Comentário'
        verbose_name_plural = 'Comentarios'
        ordering = ['-created']

    def __str__(self):
        return 'Comentário de: ' + self.name

events/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Comment
from django.core.mail import EmailMessage



class EmailEventoForm(forms.Form):
    email = forms.EmailField(
        label="Seu e-mail",
    )
    name = forms.CharField(
        label="Seu nome",
        max_length=100,
    )
    destination = forms.EmailField(
        label="E-mail do destinatário",
    )
    comment = forms.CharField(
        label="Mensagem (opcional)",
        required=False,
        widget=forms.Textarea,
    )

    def send_email(self, myevent):
        email = self.cleaned_data['email']
        name = self.cleaned_data['name']
        destination = self.cleaned_data['destination']
        comment = self.cleaned_data['comment']

        content = (
            f"Recomendo o evento: {myevent.titulo}\n"
            f"Descrição: {myevent.descricao}\n\n"
            f"Comentário de {name}: {comment}"
        )

        msg = EmailMessage(
            subject=f"{name} recomendou o evento: {myevent.titulo}",
            body=content,
            from_email='contato@mysite.com.br',
            to=[destination],
            headers={'Reply-To': email}
        )
        msg.send()



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'comment')

    def save_comment(self, evento):
        new_comment = self.save(commit=False)
        new_comment.evento = evento
        new_comment.save()
        return new_comment



class CadUserForm(UserCreationForm):
    email = forms.EmailField(
        label="E-mail",
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
        # remove os help_text padrão do Django
        help_texts = {
            "username": "",
            "email": "",
            "password1": "",
            "password2": "",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Usuário
        self.fields["username"].label = "Usuário"
        self.fields["username"].widget.attrs.update({"class": "form-control"})
        self.fields["username"].help_text = (
            '<br>'
            'Use apenas letras, números e @ . + - _.'
        )

        # E-mail
        self.fields["email"].help_text = (
            '<br>'
            'Informe um e-mail válido.'
        )

        # Senha
        self.fields["password1"].label = "Senha"
        self.fields["password1"].widget.attrs.update({"class": "form-control"})
        self.fields["password1"].help_text = (
            '<br>'
            'Use pelo menos 8 caracteres, misturando letras e números.'
        )

        # Confirmação de senha
        self.fields["password2"].label = "Confirmação de senha"
        self.fields["password2"].widget.attrs.update({"class": "form-control"})
        self.fields["password2"].help_text = (
            '<br>'
            'Repita a mesma senha digitada acima.'
        )



class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

eventos/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LogoutView, LoginView
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, FormView, CreateView

from .forms import EmailPostForm, CommentForm, CadUserForm, LoginForm
from .models import Post

class ListPostsView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'blog/post/list_posts.html'

class DetailPostView(DetailView):
    template_name = 'blog/post/detail_post.html'
    context_object_name = 'post'
    model = Post

    def _get_comments(self, id_post):
        try:
            post = Post.objects.get(pk=id_post)
            return post.comments.all()
        except Post.DoesNotExist:
            raise Http404

    def get_context_data(self, **kwargs):
        context = super(DetailPostView, self).get_context_data(**kwargs)
        context['comments'] = self._get_comments(self.object.id)
        return context


class FormPostView(FormView):
    template_name = 'blog/post/sharepost.html'
    form_class = EmailPostForm
    success_url = reverse_lazy('blog:list_posts')

    def get_post(self, id_post):
        try:
            return Post.objects.get(pk=id_post)
        except Post.DoesNotExist:
            messages.error(self.request, 'Post not found')
            return None

    def get_context_data(self, **kwargs):
        context = super(FormPostView, self).get_context_data(**kwargs)
        context['post'] = self.get_post(self.kwargs['pk'])
        return context

    def form_valid(self, form, *args, **kwargs):
        mypost = self.get_context_data()['post']
        form.send_email(mypost)
        messages.success(self.request, f'Post {mypost.title} ' f'enviado com sucesso')
        return super(FormPostView, self).form_valid(form, *args, **kwargs)

    def form_invalid(self, form, *args, **kwargs):
        mypost = self.get_context_data()['post']
        messages.error(self.request, f'Post {mypost.title} ' f'não foi enviado')
        return super(FormPostView, self).form_invalid(form, *args, **kwargs)


class comment_views(CreateView):
    template_name = 'blog/post/comment.html'
    form_class = CommentForm

    def _get_post(self, id_post):
        try:
            post = Post.objects.get(pk=id_post)
            return post
        except Post.DoesNotExist:
            messages.error(self.request, 'Post not found')

    def get_context_data(self, **kwargs):
        context = super(comment_views, self).get_context_data(**kwargs)
        context['post'] = self._get_post(self.kwargs['pk'])
        return context

    def form_valid(self, form, *args, **kwargs):
        post = self._get_post(self.kwargs['pk'])
        form.save_comment(post)
        return redirect('blog:detail_post', slug=post.slug)

    def form_invalid(self, form, *args, **kwargs):
        post = self._get_post(self.kwargs['pk'])
        messages.error(self.request, 'Comentário não enviado. Corrija os erros do formulário.')
        context = self.get_context_data(form=form, **kwargs)
        return self.render_to_response(context)

class CadUserView(CreateView):
    template_name = 'blog/users/caduser.html'
    form_class = CadUserForm
    success_url = reverse_lazy('blog:loginuser')

    def form_valid(self, form, *args, **kwargs):
        form.cleaned_data
        form.save()
        messages.success(self.request, f"Your account has been created")
        return super(CadUserView, self).form_valid(form, *args, **kwargs)

    def form_invalid(self, form, *args, **kwargs):
        messages.error(self.request, 'Account not created')
        return super(CadUserView, self).form_invalid(form, *args, **kwargs)

class LoginUserView(LoginView):
    template_name = 'blog/users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('blog:list_posts')

    def form_valid(self, form, *args, **kwargs):
        user = authenticate(self.request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        if user is not None:
            login(self.request, user)
            messages.success(self.request, f"Login successful {user.username}")
            return redirect('blog:list_posts')
        else:
            messages.error(self.request, 'Login failed')
            return redirect('blog:loginuser')
        
    def form_invalid(self, form, *args, **kwargs):
        messages.error(self.request, 'Login failed')
        return redirect('blog:loginuser')


class LogoutUserView(LogoutView):
    next_page = reverse_lazy('blog:list_posts')

events/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LogoutView, LoginView
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, FormView, CreateView

from .forms import EmailEventoForm, CommentForm, CadUserForm, LoginForm
from .models import Evento

class EventoListView(ListView):
    context_object_name = 'Eventos'
    model = Evento
    template_name = 'eventos/myevent/list_eventos.html'

class EventoDetailView(DetailView):
    context_object_name = 'evento'
    model = Evento
    template_name = 'eventos/myevent/detail_event.html'

    def _get_comments(self, id_post):
        try:
            post = Evento.objects.get(pk=id_post)
            return post.comments.all()
        except Evento.DoesNotExist:
            raise Http404

    def get_context_data(self, **kwargs):
        context = super(EventoDetailView, self).get_context_data(**kwargs)
        context['comments'] = self._get_comments(self.object.id)
        return context


class FormEventoView(FormView):
    template_name = 'eventos/myevent/eventshare.html'
    form_class = EmailEventoForm
    success_url = reverse_lazy('events:list_eventos')

    def get_post(self, pk):
        try:
            return Evento.objects.get(pk=pk)
        except Evento.DoesNotExist:
            messages.error(self.request, 'Evento não encontrado')
            return None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['myevent'] = self.get_post(self.kwargs['pk'])
        return context

    def form_valid(self, form, *args, **kwargs):
        mypost = self.get_context_data()['myevent']
        form.send_email(mypost)
        messages.success(self.request, f'Evento \"{mypost.titulo}\" enviado com sucesso')
        return super().form_valid(form, *args, **kwargs)

    def form_invalid(self, form, *args, **kwargs):
        mypost = self.get_context_data().get('myevent')
        messages.error(self.request, f'Evento \"{mypost.titulo if mypost else ""}\" não foi enviado')
        return super().form_invalid(form, *args, **kwargs)



class comment_views(CreateView):
    template_name = 'eventos/myevent/comment.html'
    form_class = CommentForm

    def _get_post(self, pk):
        try:
            evento = Evento.objects.get(pk=pk)
            return evento
        except Evento.DoesNotExist:
            messages.error(self.request, 'Evento não encontrado')

    def get_context_data(self, **kwargs):
        context = super(comment_views, self).get_context_data(**kwargs)
        context['myevent'] = self._get_post(self.kwargs['pk'])
        return context

    def form_valid(self, form, *args, **kwargs):
        post = self._get_post(self.kwargs['pk'])
        form.save_comment(post)
        return redirect('events:detail_event', slug=post.slug)

    def form_invalid(self, form, *args, **kwargs):
        post = self._get_post(self.kwargs['pk'])
        messages.error(self.request, 'Comentário não enviado. Corrija os erros do formulário.')
        context = self.get_context_data(form=form, **kwargs)
        return self.render_to_response(context)


class CadUserView(CreateView):
    template_name = "eventos/users/caduser.html"
    form_class = CadUserForm
    success_url = reverse_lazy('events:loginuser')

    def form_valid(self, form, *args, **kwargs):
        form.cleaned_data
        form.save()
        messages.success(self.request, f"Your account has been created")
        return super(CadUserView, self).form_valid(form, *args, **kwargs)

    def form_invalid(self, form, *args, **kwargs):
        messages.error(self.request, 'Account not created')
        return super(CadUserView, self).form_invalid(form, *args, **kwargs)

class LoginUserView(LoginView):
    template_name = 'eventos/users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('events:list_eventos')

    def form_valid(self, form, *args, **kwargs):
        user = authenticate(self.request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        if user is not None:
            login(self.request, user)
            return redirect('events:list_eventos')
        else:
            messages.error(self.request, 'Login failed')
            return redirect('events:loginuser')
        
    def form_invalid(self, form, *args, **kwargs):
        messages.error(self.request, 'Login failed')
        return redirect('events:loginuser')


class LogoutUserView(LogoutView):
    next_page = reverse_lazy('events:list_eventos')

events/templates/eventos/users/caduser.html
{% extends "eventos/base.html" %}
{% block titulo %} Cadastro de Usuários {% endblock %}
{% block conteudo %}
<div class="container py-5" style="max-width: 440px;">
    <div class="card shadow border-0">
        <div class="card-body p-4">
            <h2 class="mb-4 text-center text-primary">
                <i class="bi bi-person-plus"></i> Cadastre-se
            </h2>

            {% if form.errors %}
            <div class="alert alert-danger">
                <h6 class="mb-2">Erros ao cadastrar:</h6>
                <ul class="mb-0 ps-3">
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li><strong>{{ field.label }}:</strong> {{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            <form method="post" action="{% url 'events:cadastrouser' %}" novalidate>
                {% csrf_token %}

                {% for field in form %}
                <div class="mb-3">
                    <label class="form-label">
                        {{ field.label }}
                    </label>

                    {{ field }}

                    {% if field.help_text %}
                    <div class="form-text mt-1 small text-muted">
                        {{ field.help_text|safe }}
                    </div>
                    {% endif %}

                    {% for error in field.errors %}
                    <div class="invalid-feedback d-block mt-1">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}

                <button class="btn btn-primary w-100 mt-3" type="submit">
                    <i class="bi bi-check-lg"></i> Criar novo usuário
                </button>
            </form>
        </div>
    </div>
</div>
<link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
{% endblock %}

events/templates/eventos/users/login.html
{% extends "eventos/base.html" %}

{% block titulo %} Login Usuário {% endblock %}

{% block conteudo %}
<div class="container py-5" style="max-width: 440px;">
    <div class="card shadow border-0">
        <div class="card-body p-4">
            <h2 class="mb-4 text-center text-primary">
                <i class="bi bi-box-arrow-in-right"></i> Entrar
            </h2>

            {# erros gerais do form (ex: usuário/senha inválidos) #}
            {% if form.non_field_errors %}
            <div class="alert alert-danger">
                <ul class="mb-0 ps-3">
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            <form method="post" action="{% url 'events:loginuser' %}" novalidate>
                {% csrf_token %}

                {% for field in form %}
                <div class="mb-3">
                    <label class="form-label">
                        {{ field.label }}
                    </label>

                    {{ field }}

                    {% if field.help_text %}
                    <div class="form-text mt-1 small text-muted">
                        {{ field.help_text|safe }}
                    </div>
                    {% endif %}

                    {% for error in field.errors %}
                    <div class="invalid-feedback d-block mt-1">
                        {{ error }}
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}

                <button class="btn btn-primary w-100 mt-3" type="submit">
                    <i class="bi bi-box-arrow-in-right"></i> Fazer login
                </button>
            </form>

            <div class="mt-3 text-center">
                <small class="text-muted">
                    Não tem conta?
                    <a href="{% url 'events:cadastrouser' %}">Cadastre-se</a>
                </small>
            </div>
        </div>
    </div>
</div>

<link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
{% endblock %}